spring:
  cloud:
    gateway:
      routes:
      - id: r1
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customers/**
      - id: r2
        uri: lb://INVENTAIRE-SERVICE
        predicates:
        - Path=/inventaires/**